Repository dxfrontier/dx-starter-templates, pull requests merged in 2025-01, with the labels that each got.

#164 160 housekeeping add GitHub action template based on refactor
  src/base/index.ts
  src/base/project.ts
  src/base/samplecode.ts
  src/github-action/index.ts
  src/github-action/project.ts
  src/github-action/samplecode.ts
Labels: version: patch

#179 174 bug fix devcontainer postcommandscript
  .devcontainer.json
  cliff.toml
  lib/base/commitlint.d.ts
  lib/base/commitlint.js
  lib/base/config.d.ts
  lib/base/config.js
  lib/base/devcontainer.d.ts
  lib/base/devcontainer.js
  lib/base/eslint.d.ts
  lib/base/eslint.js
  lib/base/git.d.ts
  lib/base/git.js
  lib/base/github.d.ts
  lib/base/github.js
  lib/base/husky.d.ts
  lib/base/husky.js
  lib/base/prettier.d.ts
  lib/base/prettier.js
  lib/base/project.d.ts
  lib/base/project.js
  lib/base/typescript.d.ts
  lib/base/typescript.js
  lib/base/vscode.d.ts
  lib/base/vscode.js
  lib/cap-service/commitlint.js
  lib/cap-service/devcontainer.js
  lib/cap-service/eslint.js
  lib/cap-service/github.js
  lib/cap-service/index.d.ts
  lib/cap-service/index.js
  lib/cap-service/npm.d.ts
  lib/cap-service/npm.js
  lib/cap-service/prettier.js
  lib/cap-service/project.js
  lib/cap-service/samplecode.d.ts
  lib/cap-service/samplecode.js
  lib/github-action/commitlint.js
  lib/github-action/npm.d.ts
  lib/github-action/npm.js
  lib/jsii/npm.d.ts
  lib/jsii/npm.js
  lib/jsii/project.d.ts
  lib/jsii/project.js
  lib/jsii/typescript.d.ts
  lib/jsii/typescript.js
  lib/tsconfig.tsbuildinfo
  lib/types/index.d.ts
  lib/types/index.js
  lib/types/types.d.ts
  lib/types/types.js
  lib/utils.d.ts
  lib/utils.js
  package.json
  src/base/devcontainer.ts
  src/cap-service/devcontainer.ts
  test/cap-service/config/devcontainer.test.ts
  test/github-action/config/npm.test.ts
  test/jsii/config/npm.test.ts
  test/shared/devcontainer.ts
Labels: version: patch

#193 176 bug check templates
  .jsii
  API.md
  lib/.DS_Store
  lib/base/config/commitlint.js
  lib/base/config/eslint.js
  lib/base/config/husky.js
  lib/base/config/prettier.js
  lib/base/config/typescript.d.ts
  lib/base/config/typescript.js
  lib/cap-service/config/jest.js
  lib/cap-service/config/npm.js
  lib/cap-service/config/samplecode.d.ts
  lib/cap-service/config/samplecode.js
  lib/cap-service/config/typescript.d.ts
  lib/cap-service/config/typescript.js
  lib/cap-service/project.js
  lib/github-action/config/typescript.d.ts
  lib/github-action/config/typescript.js
  lib/jsii/config/npm.js
  lib/jsii/config/typescript.d.ts
  lib/jsii/config/typescript.js
  lib/tsconfig.tsbuildinfo
  lib/util/constants.d.ts
  lib/util/constants.js
  lib/util/types/index.d.ts
  lib/util/types/index.js
  lib/util/types/project.d.ts
  lib/util/types/project.js
  lib/util/types/types.d.ts
  lib/util/types/types.js
  lib/util/utils.d.ts
  lib/util/utils.js
  src/base/config/commitlint.ts
  src/base/config/eslint.ts
  src/base/config/husky.ts
  src/base/config/prettier.ts
  src/base/config/typescript.ts
  src/cap-service/config/jest.ts
  src/cap-service/config/npm.ts
  src/cap-service/config/samplecode.ts
  src/cap-service/project.ts
  src/jsii/config/npm.ts
  src/util/constants.ts
  test/cap-service/config/npm.test.ts
  test/cap-service/config/samplecode.test.ts
Labels: version: minor

#198 chore(merge): merge complete
  lib/cap-service/config/npm.js
  lib/cap-service/config/samplecode.js
  lib/cap-service/project.d.ts
  lib/tsconfig.tsbuildinfo
  src/base/config/commitlint.ts
  src/base/config/devcontainer.ts
  src/base/config/eslint.ts
  src/base/config/github.ts
  src/base/config/husky.ts
  src/base/config/npm.ts
  src/base/config/prettier.ts
  src/base/config/typescript.ts
  src/base/config/vscode.ts
  src/base/project.ts
  src/cap-service/config/jest.ts
  src/cap-service/config/npm.ts
  src/cap-service/config/samplecode.ts
  src/cap-service/project.ts
  src/jsii/project.ts
  src/util/constants.ts
  src/util/utils.ts
  test/cap-service/config/npm.test.ts
Labels: version: patch

#200 192 housekeeping eslint devdependencies must be refactored
  .jsii
  .projen/deps.json
  lib/base/config/commitlint.js
  lib/base/config/devcontainer.js
  lib/base/config/eslint.js
  lib/base/config/github.js
  lib/base/config/husky.js
  lib/base/config/npm.js
  lib/base/config/prettier.js
  lib/base/config/typescript.js
  lib/base/config/vscode.js
  lib/base/configs/commitlint.d.ts
  lib/base/configs/commitlint.js
  lib/base/configs/devcontainer.d.ts
  lib/base/configs/devcontainer.js
  lib/base/configs/eslint.d.ts
  lib/base/configs/eslint.js
  lib/base/configs/git.d.ts
  lib/base/configs/git.js
  lib/base/configs/github.d.ts
  lib/base/configs/github.js
  lib/base/configs/husky.d.ts
  lib/base/configs/husky.js
  lib/base/configs/jest.d.ts
  lib/base/configs/jest.js
  lib/base/configs/npm.d.ts
  lib/base/configs/npm.js
  lib/base/configs/options.d.ts
  lib/base/configs/options.js
  lib/base/configs/prettier.d.ts
  lib/base/configs/prettier.js
  lib/base/configs/samplecode.d.ts
  lib/base/configs/samplecode.js
  lib/base/configs/typescript.d.ts
  lib/base/configs/typescript.js
  lib/base/configs/vscode.d.ts
  lib/base/configs/vscode.js
  lib/base/project.js
  lib/cap-service/config/jest.js
  lib/cap-service/config/npm.js
  lib/cap-service/config/samplecode.js
  lib/cap-service/jest.d.ts
  lib/cap-service/jest.js
  lib/cap-service/project.js
  lib/jsii/project.js
  lib/tsconfig.tsbuildinfo
  lib/util/constants.d.ts
  lib/util/constants.js
  lib/util/utils.d.ts
  lib/util/utils.js
  package-lock.json
  package.json
  src/base/config/eslint.ts
  src/util/constants.ts
  test/cap-service/config/npm.test.ts
  test/github-action/config/npm.test.ts
  test/jsii/config/npm.test.ts
Labels: version: patch

#202 feat(sqlite): added sqlite as default db
  .jsii
  lib/cap-service/config/npm.js
  lib/tsconfig.tsbuildinfo
  lib/util/constants.d.ts
  lib/util/constants.js
  src/cap-service/config/npm.ts
  src/util/constants.ts
  test/cap-service/config/npm.test.ts
Labels: priority: critical, version: patch, context: cap project

#207 refactor(project.ts): removed unused code from cap-service
  src/cap-service/project.ts
  src/util/utils.ts
Labels: version: patch, context: cap project

#209 chore(readme): updated main readme
  README.md
Labels: version: patch
